name: example
description: An example.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_node:
    path: ..

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  uses-material-design: true