name: web_node
version: 0.2.1
description: A cross-platform widget for displaying DOM nodes (iframes, etc.) in Flutter
  applications. Uses real DOM nodes in browsers and webview_flutter in Android/iOS.
homepage: https://github.com/dint-dev/web_node

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  universal_html: ^2.0.4
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0