name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:stable

    steps:
      - uses: actions/checkout@v1

      - name: Upgrade Flutter
        run: flutter config --no-analytics && flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test